<li>
        <div class="room-pic fl"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="225" height="118"></a></div>
        <div class="room-left fl">
          <div class="news-title"><a href="[field:arcurl/]">[field:title/]</a></div>
          <div class="ubb pb14">[field:description/]</div>
          <div class="dining-date fl pr30">营业时间：<span>[field:ycsj/]</span></div>
        </div>
        <!--room-left end-->
        <div class="room-right fr">
          <div class="li1">菜肴特色：</div>
          <div class="li3" style="font-size:12px; text-align:left; padding:12px 5px 0 12px;">[field:description/]</div>
          <div class="more pl10 mt20"><a href="[field:arcurl/]">查看详细</a></div>
        </div>
        <!--room-right end-->
      </li>