<li>
        <div class="room-pic fl"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="225" height="118"></a></div>
        <div class="room-left fl">
          <div class="news-title"><a href="[field:arcurl/]">[field:title/]</a></div>
          <div class="ubb pb14 pt12">[field:description/]</div>
          <div class="area fl pr30">使用面积：<span>[field:symj/]/㎡</span></div>
          <div class="broadband fl">宽带：<span>免费</span></div>
        </div>
        <!--room-left end-->
        <div class="room-right fr">
          <div class="li1">今日价格：</div>
          <div class="li2"><span>[field:price/]</span>RMB</div>
          <div class="booking-but pl10"><a href="booking_room_con.php?id=[field:id/]">立即预订</a></div>
          <div class="more pl10 pt3"><a href="[field:arcurl/]">查看详细</a></div>
        </div>
        <!--room-right end-->
      </li>