<div class="services pt33 c">
      <div class="services-top c">
        <div class="li1 fl"><img src="[field:litpic/]"></div>
        <div class="li2 fl f22">[field:title/]</div>
      </div>
      <!--services-top end-->
      <div class="ubb pt17">[field:description/] </div>
      <ul class="services-pic services-pic2 pt33 fl">
        [field:id function="Getimgs(@me,172,119, 4,'')"/] 
      </ul>
      <!--services-pic end-->
      <div class="more2 fr"><a href="[field:arcurl/]">更多图片</a></div>
    </div>