<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,173);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",213,264);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3252,3287);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4306,4335);
$z[5][4]['name']="position";
$z[6]=Array("channel"," <a href='[field:typeurl/]'>[field:typename/]</a> ",4631,4785);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='on'>~typename~</a>";
$z[7]=Array("field","",4976,4996);
$z[7][4]['name']="litpic";
$z[8]=Array("field","",5257,5276);
$z[8][4]['name']="title";
$z[9]=Array("field","",5318,5336);
$z[9][4]['name']="body";
$z[10]=Array("field","",5525,5544);
$z[10][4]['name']="price";
$z[11]=Array("field","",5637,5653);
$z[11][4]['name']="id";
$z[12]=Array("include","",5856,5894);
$z[12][4]['filename']="footer2.htm";

?>