<li class="c">
                <div class="preferential-left fl"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="125" height="95"></a></div>
                <div class="preferential-right fl">
                  <div class="li1"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
                </div>
                <!--preferential-right end--> 
              </li>