<li>
          <div class="special-pic"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="298" height="156"></a></div>
          <div class="news-title pt17"><a href="[field:arcurl/]">[field:title/]</a></div>
          <div class="price"><span class="a2">RMB</span><span class="a1">&nbsp;[field:price/]元净价/位</span></div>
          <div class="ubb pt12"> [field:description/]</div>
          <div class="special-date">[field:hdsj/]</div>
          <!--<div class="booking-but fl"><a href="booking_package.php?id=10&type=[field:id/]">立即预订</a></div>-->
          <div class="more fl"><a href="[field:arcurl/]">查看详细</a></div>
        </li>