<?php
$z[0]=Array("channel"," <a href='[field:typelink/]'>[field:typename/]</a>|",95,199);
$z[0][4]['type']="son";
$z[0][4]['typeid']="7";
$z[1]=Array("global","",213,237);
$z[1][4]['name']="cfg_weibo";
$z[2]=Array("global","",389,410);
$z[2][4]['name']="cfg_qq";
$z[3]=Array("global","",476,497);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",669,693);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",730,753);
$z[5][4]['name']="cfg_copy";
$z[6]=Array("global","",934,958);
$z[6][4]['name']="cfg_beian";

?>