<?php
$z[0]=Array("channel"," <a href='[field:typelink/]'>[field:typename/]</a>|",50,154);
$z[0][4]['type']="son";
$z[0][4]['typeid']="7";
$z[1]=Array("global","",168,192);
$z[1][4]['name']="cfg_weibo";
$z[2]=Array("global","",344,365);
$z[2][4]['name']="cfg_qq";
$z[3]=Array("global","",431,452);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",621,645);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",682,705);
$z[5][4]['name']="cfg_copy";
$z[6]=Array("global","",886,910);
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",1216,1237);
$z[7][4]['name']="cfg_qq";

?>