<?php
$z[0]=Array("global","",64,90);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",134,164);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",201,228);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("channel","\r\n    <li><a href='[field:typeurl/]'  > [field:typename/]</a></li>\r\n    ",5259,5381);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[4]=Array("php","echo date('Y-m-d',time());",6277,6324);
$z[5]=Array("php","echo date('Y-m-d',time()+3600*24);",6595,6650);
$z[6]=Array("arclist","\r\n                <li><a href=\"javascript:;\" title=\"[field:title/]\" data-value=\"[field:id/]\">[field:title/]<font style=\"float:right; color:#ee782f\">&yen;[field:price/]&nbsp;&nbsp;</font></a></li>\r\n                ",7658,7946);
$z[6][4]['row']="15";
$z[6][4]['addfields']="price";
$z[6][4]['channelid']="18";
$z[7]=Array("arclist","\r\n              <li class=\"c\">\r\n                <div class=\"preferential-left fl\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"125\" height=\"95\"></a></div>\r\n                <div class=\"preferential-right fl\">\r\n                  <div class=\"li1\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></div>\r\n                </div>\r\n                <!--preferential-right end--> \r\n              </li>\r\n              ",8948,9456);
$z[7][4]['row']="15";
$z[7][4]['channelid']="17";
$z[8]=Array("include","",10151,10188);
$z[8][4]['filename']="footer.htm";

?>