<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3266,3301);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4322,4351);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n     <a href='[field:typeurl/]'>[field:typename/]</a> \r\n	    ",4659,4835);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='on'>~typename~</a>";
$z[7]=Array("field","",4930,4951);
$z[7][4]['name']="content";
$z[8]=Array("include","",5158,5196);
$z[8][4]['filename']="footer2.htm";

?>