<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3266,3301);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4320,4349);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n        <li>\r\n          <div class=\"special-pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"298\" height=\"156\"></a></div>\r\n          <div class=\"news-title pt17\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n          <div class=\"price\"><span class=\"a2\">RMB</span><span class=\"a1\">&nbsp;[field:price/]元净价/位</span></div>\r\n          <div class=\"ubb pt12\"> [field:description/]</div>\r\n          <div class=\"special-date\">[field:hdsj/]</div>\r\n          <!--<div class=\"booking-but fl\"><a href=\"booking_package.php?id=10&type=[field:id/]\">立即预订</a></div>-->\r\n          <div class=\"more fl\"><a href=\"[field:arcurl/]\">查看详细</a></div>\r\n        </li>\r\n        \r\n       ",4705,5485);
$z[6][4]['pagesize']="6";
$z[6][4]['channelid']="17";
$z[6][4]['addfields']="hdsj,price";
$z[7]=Array("pagelist","",6333,6411);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",6549,6587);
$z[8][4]['filename']="footer2.htm";

?>