<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3266,3301);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4301,4330);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n    <div class=\"services pt33 c\">\r\n      <div class=\"services-top c\">\r\n        <div class=\"li1 fl\"><img src=\"[field:litpic/]\"></div>\r\n        <div class=\"li2 fl f22\">[field:title/]</div>\r\n      </div>\r\n      <!--services-top end-->\r\n      <div class=\"ubb pt17\">[field:description/] </div>\r\n      <ul class=\"services-pic services-pic2 pt33 fl\">\r\n        [field:id function=\"Getimgs(@me,172,119, 4,'')\"/] \r\n      </ul>\r\n      <!--services-pic end-->\r\n      <div class=\"more2 fr\"><a href=\"[field:arcurl/]\">更多图片</a></div>\r\n    </div>  ",4640,5233);
$z[6][4]['pagesize']="6";
$z[6][4]['channelid']="2";
$z[7]=Array("include","",5657,5695);
$z[7][4]['filename']="footer2.htm";

?>