<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3266,3301);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4299,4328);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n      <li>\r\n        <div class=\"room-pic fl\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"225\" height=\"118\"></a></div>\r\n        <div class=\"room-left fl\">\r\n          <div class=\"news-title\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n          <div class=\"ubb pb14\">[field:description/]</div>\r\n          <div class=\"dining-date fl pr30\">营业时间：<span>[field:ycsj/]</span></div>\r\n        </div>\r\n        <!--room-left end-->\r\n        <div class=\"room-right fr\">\r\n          <div class=\"li1\">菜肴特色：</div>\r\n          <div class=\"li3\" style=\"font-size:12px; text-align:left; padding:12px 5px 0 12px;\">[field:description/]</div>\r\n          <div class=\"more pl10 mt20\"><a href=\"[field:arcurl/]\">查看详细</a></div>\r\n        </div>\r\n        <!--room-right end-->\r\n      </li>\r\n      ",4655,5547);
$z[6][4]['pagesize']="6";
$z[6][4]['channelid']="2";
$z[6][4]['addfields']="hdsj,price";
$z[7]=Array("pagelist","",6400,6478);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",6639,6677);
$z[8][4]['filename']="footer2.htm";

?>