<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3266,3301);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4323,4352);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n     <a href='[field:typeurl/]'>[field:typename/]</a> \r\n	    ",4664,4840);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='on'>~typename~</a>";
$z[7]=Array("list"," <li>\r\n        <div class=\"room-pic fl\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"225\" height=\"118\"></a></div>\r\n        <div class=\"room-left fl\">\r\n          <div class=\"news-title\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n          <div class=\"ubb pb14 pt12\">[field:description/]</div>\r\n          <div class=\"area fl pr30\">使用面积：<span>[field:symj/]/㎡</span></div>\r\n          <div class=\"broadband fl\">宽带：<span>免费</span></div>\r\n        </div>\r\n        <!--room-left end-->\r\n        <div class=\"room-right fr\">\r\n          <div class=\"li1\">今日价格：</div>\r\n          <div class=\"li2\"><span>[field:price/]</span>RMB</div>\r\n          <div class=\"booking-but pl10\"><a href=\"booking_room_con.php?id=[field:id/]\">立即预订</a></div>\r\n          <div class=\"more pl10 pt3\"><a href=\"[field:arcurl/]\">查看详细</a></div>\r\n        </div>\r\n        <!--room-right end-->\r\n      </li>\r\n       ",4931,5945);
$z[7][4]['pagesize']="6";
$z[7][4]['channelid']="18";
$z[7][4]['addfields']="hdsj,price";
$z[8]=Array("pagelist","",6785,6863);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",7001,7039);
$z[9][4]['filename']="footer2.htm";

?>